### ISSUE TITLE
Errors reported via my dapp involving metamask

### ISSUE THREAD

**Issue by wighawag** [MetaMask/hello#28]
Hi I got some error reported from my beta test dapp at http://test.etherplay.io/catchme
This involve metamask :

BigNumber Error: new BigNumber() not a number: true
  at D(chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:11998:27359)
  at new e(chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:11998:25283)
  at new e(chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:11998:24711)
  at Object.x [as toBigNumber](chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:11995:19439)
  at a [as outputFormatter](chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:11996:1394)
  at i.formatOutput(chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:11996:13652)
  at apply(raven.js:379:28)

**Comment by wighawag** [comment]
It could well be from a bug on my side though (maybe giving wrong data?)

**Comment by flyswatter** [comment]
First off, sorry for the slow reply, been a busy time!

I haven't seen this bug in a while, I've played your game with no problems.  Have you seen this again since?

**Comment by wighawag** [comment]
No worries,
I never seen that bug myself, but my error reporting system has reported few of them when the competition was at its peak in term of players. I am going to run another competition soon (in 2-3 weeks time) . I ll let you know if it comes up again at that point.

**Comment by flyswatter** [comment]
Thanks!  I'll close for now, but if you get one of those reports, could you try sending one of the reporters here to help us debug?
